#!/bin/bash

while [ "1" != "2" ]; do
TEST=$(ping -c 1 -w 1 -t 10 222.124.158.86 | grep "64 bytes" | awk -F= '{ print $2 }' | awk '{ print $1 }')

  if [ "$TEST" = "" ]; then
     echo "Not connected ,  you must login"
     curl -d accept=Login -d auth_user="<your own user name>"  -d auth_pass="<your own pass>" <captive portal address> > /dev/null
  elif [ "$TEST" = "1" ]; then
     echo "Connected"
  fi

sleep 5
done
